### PR TITLE
Update syntax

### PR DESCRIPTION
**Pull request by brunoparga**
I have updated three pieces of syntax throughout the app:

- partial rendering, where the partial argument used to be a value of the options hash but is now just the first argument to `render`
- Hash syntax, replacing `:symbol => value` with `symbol: value`
- ERB syntax, eliminating the dash from `<%- -%>`

### CODE REVIEW

**Comment by brunoparga** [comment]
Also on partial rendering: the `locals` hash was eliminated, its contents now are passed straight to `render`.

**Comment by michaelwebb76** [comment]
@brunoparga are you running the specs before submitting your PRs? This code doesn't even run.

**Comment by brunoparga** [comment]
Oops. No, sorry, didn't run them for this particular PR, my bad. Lemme see what happened.

**Comment by brunoparga** [comment]
All tests run and pass.

**Comment by michaelwebb76** [comment]
I'll see what I can do about getting our CI up and running on this as well.

**Comment by michaelwebb76** [comment]
Although (disturbingly) none of the tests fail, removing `locals:` from the `render` method in views actually breaks the site. Try adding yourself to a group and then viewing the group.

**Comment by brunoparga** [comment]
@michaelwebb76 I believe I have solved the remaining issue with HAML.

**Comment by michaelwebb76** [comment]
LGTM

**Pull request merged**
