### PR TITLE
Proper scoring rule redux

### PR DESCRIPTION
**Pull request by jaysonvirissimo**
Here's a preliminary implementation of calibration scoring. [This](https://github.com/tricycle/predictionbook/commit/7b551990f2f84fdec815aff40afe49fce88e9d54) was a earlier attempt from which I drew inspiration, but it was far too slow for production use. This still has many possible performance enhancements, but I wanted to get this out there for criticism before I spend any time optimizing.

Once scores are stored in the `users` table, adding a (performant) leaderboard like [this](https://github.com/tricycle/predictionbook/pull/56) should become trivial.

### CODE REVIEW

**Comment by matthewfallshaw** [comment]
I don't think we want a recency limit on the first implementation here. Jayson has implemented bayes score properly, and that's a well established way to do this. A future extension would be to allow users to choose a time limit, or show multiple scores (say all time, 12 months, one month).

I do worry that this will be slow for our more active members, and think that a pure SQL implementation would be much faster.
@jaysonvirissimo Have you done any load testing? Gwern has ~ 2263 predictions. If that takes < 2s to calculate I'm fairly happy. (You might protect the server by limiting the predictions included to the most recent x for some value of x that does take < 2s to calculate.)

**Comment by jaysonvirissimo** [comment]
@moggyboy, @matthewfallshaw: thanks for your input. I may be able to attempt some load testing this weekend to ensure it is under the 2 second limit, and make further optimizations (whether that means re-writing in pure SQL or caching the number of scorable wagers used in the last calculation) if warranted.

**Comment by jaysonvirissimo** [comment]
### Testing Setup
Modified `seeds.rb` to use `DATA_SIZE = 10000` instead of `DATA_SIZE = 1000`, and wrapped `User#reset_score` with the following:
```
def reset_score
    start_time = Time.current
    update(score: ScoreCalculator.calculate(wagers))
    finish_time = Time.current
    puts "Resetting the score took #{(finish_time - start_time).round} seconds."
  end
```
Using the following development environment:
```
MacBook Air (13-inch, Early 2015)
2.2 GHz Intel Core i7
8 GB 1600 MHz DDR3
```
### Results
`Resetting the score took 4 seconds.`

**Comment by jaysonvirissimo** [comment]
I won't be working on this any for the next 2 weeks, so feel free to extend/improve this in the meantime (or deploy as is, if the performance characteristics are good enough).

**Comment by moggyboy** [comment]
Closing this in favour of https://github.com/tricycle/predictionbook/pull/121 so I can merge in master and tweak.

**Pull request closed without merging**
